# Generated by Django 4.2.9 on 2024-01-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="The Review text.")),
                (
                    "rating",
                    models.IntegerField(help_text="The rating the reviewer has given."),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the review was created.",
                    ),
                ),
                (
                    "date_edited",
                    models.DateTimeField(
                        help_text="The date and time the review was last edited.",
                        null=True,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="The Book that this review is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.book",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
